### ISSUE TITLE
Is it possible to have graph that compare countries population against confirmed cases & death?

### ISSUE THREAD

**Issue by ariefbayu** [github/covid19-dashboard#58]
Is it possible to add graph that compares countries population against confirmed cases & death?

**Comment by hamelsmu** [comment]
We have a pending one here https://github.com/github/covid19-dashboard/blob/master/_drafts/2020-03-19-cases-and-deaths-per-million.ipynb

However, I think the visualization is likely to be misleading.  This is because your count of cases is related to the number of tests you do.  South Korea, for example has tested its population widely, whereas the US has seen a dearth of testing.   

This ends up with a graph like this

![image](https://user-images.githubusercontent.com/1483922/77133935-30e57d80-6a22-11ea-9053-931ff7426488.png)

Which is highly misleading, and I'm afraid causees more confusion than value.  A better idea would be to not divide by the population, but by the `# of tests administered`.   

Welcome any discussion and thoughts. 


cc: @jbduarte
